### ISSUE TITLE
Date text vertical alignment incorrect on iOS

### ISSUE THREAD

**Issue by iusama46** [ManasMakde/react-native-deadsimple-calendar#1]
Working fine on Android but there's a bug for iOS

<img width="541" alt="image" src="https://github.com/user-attachments/assets/e69bf1fc-d983-4d22-8b1c-76f11ba9538f">

**Comment by ManasMakde** [comment]
@iusama46 Thanks for reporting!
The issue has been fixed in [v1.2.2](https://www.npmjs.com/package/react-native-deadsimple-calendar/v/1.2.2) / commit 87f72e742ad3d74f89a0f1f214606951439c84f8

![image](https://github.com/user-attachments/assets/ac90b6b6-e5cb-46db-abc7-b550e68be2af)


Let me know if there are any more bugs otherwise please close this as solved
